# Generated by Django 4.0 on 2022-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=254)),
                ('project_image', models.ImageField(upload_to='')),
                ('project_description', models.TextField()),
                ('project_github_url', models.URLField()),
                ('project_deployed_url', models.URLField()),
            ],
        ),
    ]
