# Generated by Django 4.0 on 2022-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='frameworks_used',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='languages_used',
            field=models.CharField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
